name: Glycoinformatics Consortium Developer Site
description: Communication point for glycoscientists to contact glycoinformaticians
url:  http://glic.glycoinfo.org
#exclude: [deprecated]
exclude: ['vendor']
safe: true
highlighter: rouge
markdown: kramdown
paginate: 2
paginate_path: "/blog/page:num/"
permalink: pretty
#permalink: :categories/:title
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data', 'superscript']
gems: [jekyll-paginate]


title: "Glycoinformatics Consortium "
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman